name: Test & Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: news_api_ci
          postgresql user: news_user
          postgresql password: news_password

      - name: Run tests
        run: PGDATABASE=news_api_ci PGUSER=news_user PGPASSWORD=news_password npm t

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to render
        run: curl ${{secrets.RENDER_DEPLOYHOOK_URL}}